baseURL = "https://daviddiener.de/"
languageCode = "en-us"
theme = "PaperModX"
title = "David Diener"

enableRobotsTXT= true
buildDrafts= false
buildFuture= false
buildExpired= false
pygmentsUseClasses= true

googleAnalytics = "G-92F8E6STKT"

timeout =  90000

[minify]
disableXML = true
minifyOutput = true


[params]
env = "production"
title = "David Diener"
description = "The personal blog of David Diener."
keywords = [ "Blog", "Portfolio", "Gamedev", "Webdev", "Studies", "Research", "David Diener"]
author = "David Diener"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false
TocSide = "left"
EnableInstantClick = true

[params.assets]
favicon = "favicon.ico" 

[params.homeInfoParams]
Title = "Hi there \U0001F44B"
Content = "This is my space for things I find worth sharing about my studies, web- & game development."

[[params.socialIcons]]
name = "github-simple"
url = "https://github.com/daviddiener"

[[params.socialIcons]]
name = "linkedin-simple"
url = "https://www.linkedin.com/in/david-diener"


[[params.socialIcons]]
name = "twitter-simple"
url = "https://twitter.com/diener_david_"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.cover]
hidden = false
hiddenInList = true
hiddenInSingle = false

[[menu.main]]
name = "Server Health"
url = "/server_health/"
weight = 9

[[menu.main]]
name = "Archive"
url = "/archive/"
weight = 10

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
name = "DME"
url = "https://dme.daviddiener.de"
weight = 30
[menu.main.params]
external = true

[[menu.main]]
name = "Odyssey"
url = "https://odyssey.daviddiener.de"
weight = 31
[menu.main.params]
external = true

[[menu.main]]
name = "Odyssey API"
url = "/odyssey_api"
weight = 31
[menu.main.params]
external = true

[[menu.main]]
name = "Apollon"
url = "https://davidjs.itch.io/apollon"
weight = 32
[menu.main.params]
external = true

[markup.goldmark.renderer]
unsafe= true