baseURL = "https://daviddiener.de/"
languageCode = "en-us"
theme = "PaperMod"
title = "David Diener"
googleAnalytics = "G-92F8E6STKT"


[params]
env = "production"
title = "David Diener"
description = "The personal blog of David Diener."
keywords = [ "Blog", "Portfolio", "Gamedev", "Webdev", "Studies", "Research", "David Diener"]
author = "David Diener"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
ShowCodeCopyButtons = true

[params.assets]
favicon = "favicon.ico" 

[params.homeInfoParams]
Title = "Hi there \U0001F44B"
Content = "My space for resources on my studies, web- & game development."

[[params.socialIcons]]
name = "github"
url = "https://github.com/daviddiener"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/david-diener"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[[menu.main]]
name = "Server Health"
url = "/server_health/"
weight = 9

[[menu.main]]
name = "Archive"
url = "/archive/"
weight = 10

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
name = "DME"
url = "https://dme.daviddiener.de/"
weight = 30

[[menu.main]]
name = "Odyssey"
url = "https://odyssey.daviddiener.de/"
weight = 31

[[menu.main]]
name = "Apollon"
url = "https://davidjs.itch.io/apollon"
weight = 32

[markup.goldmark.renderer]
unsafe= true